/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CaseRecord = IDL.Record({
  'caseNumber' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'forwardDate' : IDL.Opt(IDL.Text),
  'manualNote' : IDL.Text,
  'crimeNumber' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'getAllRecords' : IDL.Func([], [IDL.Vec(CaseRecord)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CaseRecord = IDL.Record({
    'caseNumber' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'forwardDate' : IDL.Opt(IDL.Text),
    'manualNote' : IDL.Text,
    'crimeNumber' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'getAllRecords' : IDL.Func([], [IDL.Vec(CaseRecord)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };